---
- name: a play to back up ios devices
  hosts: ios

  tasks:
    - name: back up IOS config
      ios_config:
        backup: yes

- name: a play to back up vyos devices
  hosts: vyos

  tasks:
    - name: back up VyOS config
      vyos_config:
        backup: yes
