---
- name: play to configure OSPF
  hosts: network
  vars:
  - vyos_ospf_template: j2/vyos-ospf.j2
  - ios_ospf_template: j2/ios-ospf.j2

  tasks:

  - name: configure ospf on VyOS
    vyos_config:
      src: "{{ vyos_ospf_template }}"
    when: ansible_network_os == 'vyos'
    
  - name: configure ospf on IOS
    ios_config:
      src: "{{ ios_ospf_template }}"
    when: ansible_network_os == 'ios'
